/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Controller.CadastroController;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JSeparator;
import javax.swing.JTextField;

/**
 *
 * @author vinic
 */
public class TelaCadastro extends javax.swing.JFrame {

    private final CadastroController controller;

    /**
     * Creates new form TelaCadastroTeste
     */
    public TelaCadastro() {
        initComponents();
        controller = new CadastroController(this);
        boxCargo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCadastroUsuario = new javax.swing.JPanel();
        lblCadastroUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblDados = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblNascimento = new javax.swing.JLabel();
        txtNascimento = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        lblSexo = new javax.swing.JLabel();
        boxGenero = new javax.swing.JComboBox<>();
        lblTelefone = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblCargo = new javax.swing.JLabel();
        boxCargo = new javax.swing.JComboBox<>();
        lblSenha = new javax.swing.JLabel();
        lblConfirmarSenha = new javax.swing.JLabel();
        pswRepeteSenha = new javax.swing.JPasswordField();
        pswSenha = new javax.swing.JPasswordField();
        lblCargo1 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Primeiro Acesso ");
        getContentPane().setLayout(null);

        pnlCadastroUsuario.setBackground(new java.awt.Color(78, 76, 76));
        pnlCadastroUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));

        lblCadastroUsuario.setBackground(new java.awt.Color(0, 0, 0));
        lblCadastroUsuario.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 25)); // NOI18N
        lblCadastroUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblCadastroUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadastroUsuario.setText("Cadastro Usuario");
        lblCadastroUsuario.setToolTipText("");

        jSeparator1.setForeground(new java.awt.Color(98, 55, 13));

        lblDados.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        lblDados.setForeground(new java.awt.Color(255, 255, 255));
        lblDados.setText("Informe todos os seus dados abaixo.");

        lblNome.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome Completo:");

        lblNascimento.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        lblNascimento.setForeground(new java.awt.Color(255, 255, 255));
        lblNascimento.setText("Dt. Nasc:");

        lblCpf.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        lblCpf.setForeground(new java.awt.Color(255, 255, 255));
        lblCpf.setText("CPF:");

        lblEmail.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("E-mail:");

        btnCadastrar.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblSexo.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        lblSexo.setForeground(new java.awt.Color(255, 255, 255));
        lblSexo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSexo.setText("Sexo:");
        lblSexo.setToolTipText("");
        lblSexo.setAlignmentY(1.5F);

        boxGenero.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        boxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Não Binario" }));
        boxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxGeneroActionPerformed(evt);
            }
        });

        lblTelefone.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTelefone.setText("Telefone:");
        lblTelefone.setToolTipText("");
        lblTelefone.setAlignmentY(1.5F);

        txtId.setFont(new java.awt.Font("Franklin Gothic Book", 0, 11)); // NOI18N

        lblCargo.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        lblCargo.setForeground(new java.awt.Color(255, 255, 255));
        lblCargo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCargo.setText("ID:");
        lblCargo.setToolTipText("");
        lblCargo.setAlignmentY(1.5F);

        boxCargo.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        boxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione seu Cargo", "Gerente", "Cabeleireiro/Barbeiro", "Visagista", "Recepcionista", "Contabilidade" }));
        boxCargo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                boxCargoFocusGained(evt);
            }
        });
        boxCargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxCargoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boxCargoMouseEntered(evt);
            }
        });
        boxCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxCargoActionPerformed(evt);
            }
        });

        lblSenha.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSenha.setText("Senha:");
        lblSenha.setToolTipText("");
        lblSenha.setAlignmentY(1.5F);

        lblConfirmarSenha.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        lblConfirmarSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmarSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfirmarSenha.setText("Confirmar Senha:");
        lblConfirmarSenha.setToolTipText("");
        lblConfirmarSenha.setAlignmentY(1.5F);

        lblCargo1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        lblCargo1.setForeground(new java.awt.Color(255, 255, 255));
        lblCargo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCargo1.setText("Cargo:");
        lblCargo1.setToolTipText("");
        lblCargo1.setAlignmentY(1.5F);

        txtTelefone.setFont(new java.awt.Font("Franklin Gothic Book", 0, 11)); // NOI18N

        javax.swing.GroupLayout pnlCadastroUsuarioLayout = new javax.swing.GroupLayout(pnlCadastroUsuario);
        pnlCadastroUsuario.setLayout(pnlCadastroUsuarioLayout);
        pnlCadastroUsuarioLayout.setHorizontalGroup(
            pnlCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroUsuarioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblCadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroUsuarioLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(lblDados, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCadastroUsuarioLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastroUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroUsuarioLayout.createSequentialGroup()
                        .addComponent(btnCadastrar)
                        .addGap(26, 26, 26)
                        .addComponent(btnVoltar))
                    .addGroup(pnlCadastroUsuarioLayout.createSequentialGroup()
                        .addComponent(lblNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCadastroUsuarioLayout.createSequentialGroup()
                        .addGroup(pnlCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCadastroUsuarioLayout.createSequentialGroup()
                                .addComponent(lblCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lblNome))
                            .addGroup(pnlCadastroUsuarioLayout.createSequentialGroup()
                                .addComponent(lblSexo)
                                .addGap(10, 10, 10)
                                .addComponent(boxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnlCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCadastroUsuarioLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCadastroUsuarioLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(lblCpf)
                                .addGap(10, 10, 10)
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCadastroUsuarioLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(lblTelefone)
                                .addGap(10, 10, 10)
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlCadastroUsuarioLayout.createSequentialGroup()
                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(lblCargo1)
                        .addGap(10, 10, 10)
                        .addComponent(boxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCadastroUsuarioLayout.createSequentialGroup()
                        .addComponent(lblSenha)
                        .addGap(10, 10, 10)
                        .addComponent(pswSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblConfirmarSenha)
                        .addGap(10, 10, 10)
                        .addComponent(pswRepeteSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
        );
        pnlCadastroUsuarioLayout.setVerticalGroup(
            pnlCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroUsuarioLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnlCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCadastroUsuarioLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblDados)))
                .addGap(30, 30, 30)
                .addGroup(pnlCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pnlCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pnlCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(boxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pnlCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCargo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCadastroUsuarioLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(pnlCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pswSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pswRepeteSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(pnlCadastroUsuario);
        pnlCadastroUsuario.setBounds(30, 30, 740, 440);

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Imagens/TElamenu.jpg"))); // NOI18N
        getContentPane().add(lblImagem);
        lblImagem.setBounds(0, 0, 810, 520);

        setSize(new java.awt.Dimension(826, 544));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxGeneroActionPerformed

    private void boxCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxCargoActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
            this.controller.salvaUsuario();
            JOptionPane.showMessageDialog(null, "Dados Salvo com Sucesso!!");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao Salvar esse usuario o codigo do erro é " + ex);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void boxCargoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_boxCargoFocusGained

    }//GEN-LAST:event_boxCargoFocusGained

    private void boxCargoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxCargoMouseEntered

    }//GEN-LAST:event_boxCargoMouseEntered

    private void boxCargoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxCargoMouseClicked
        JOptionPane.showMessageDialog(null, "Apenas Gerentes Podem definir cargo");
    }//GEN-LAST:event_boxCargoMouseClicked

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed

        TelaLogin t;
        t = new TelaLogin();
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCargo;
    private javax.swing.JComboBox<String> boxGenero;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCadastroUsuario;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCargo1;
    private javax.swing.JLabel lblConfirmarSenha;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDados;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JPanel pnlCadastroUsuario;
    private javax.swing.JPasswordField pswRepeteSenha;
    private javax.swing.JPasswordField pswSenha;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getBoxCargo() {
        return boxCargo;
    }

    public void setBoxCargo(JComboBox<String> boxCargo) {
        this.boxCargo = boxCargo;
    }

    public JComboBox<String> getBoxGenero() {
        return boxGenero;
    }

    public void setBoxGenero(JComboBox<String> boxGenero) {
        this.boxGenero = boxGenero;
    }

    public JButton getBtnCadastrar() {
        return btnCadastrar;
    }

    public void setBtnCadastrar(JButton btnCadastrar) {
        this.btnCadastrar = btnCadastrar;
    }

    public JButton getBtnVoltar() {
        return btnVoltar;
    }

    public void setBtnVoltar(JButton btnVoltar) {
        this.btnVoltar = btnVoltar;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JLabel getLblCadastroUsuario() {
        return lblCadastroUsuario;
    }

    public void setLblCadastroUsuario(JLabel lblCadastroUsuario) {
        this.lblCadastroUsuario = lblCadastroUsuario;
    }

    public JLabel getLblCargo() {
        return lblCargo;
    }

    public void setLblCargo(JLabel lblCargo) {
        this.lblCargo = lblCargo;
    }

    public JLabel getLblCargo1() {
        return lblCargo1;
    }

    public void setLblCargo1(JLabel lblCargo1) {
        this.lblCargo1 = lblCargo1;
    }

    public JLabel getLblConfirmarSenha() {
        return lblConfirmarSenha;
    }

    public void setLblConfirmarSenha(JLabel lblConfirmarSenha) {
        this.lblConfirmarSenha = lblConfirmarSenha;
    }

    public JLabel getLblCpf() {
        return lblCpf;
    }

    public void setLblCpf(JLabel lblCpf) {
        this.lblCpf = lblCpf;
    }

    public JLabel getLblDados() {
        return lblDados;
    }

    public void setLblDados(JLabel lblDados) {
        this.lblDados = lblDados;
    }

    public JLabel getLblEmail() {
        return lblEmail;
    }

    public void setLblEmail(JLabel lblEmail) {
        this.lblEmail = lblEmail;
    }


    public JLabel getLblImagem() {
        return lblImagem;
    }

    public void setLblImagem(JLabel lblImagem) {
        this.lblImagem = lblImagem;
    }

    public JLabel getLblNascimento() {
        return lblNascimento;
    }

    public void setLblNascimento(JLabel lblNascimento) {
        this.lblNascimento = lblNascimento;
    }

    public JLabel getLblNome() {
        return lblNome;
    }

    public void setLblNome(JLabel lblNome) {
        this.lblNome = lblNome;
    }

    public JLabel getLblSenha() {
        return lblSenha;
    }

    public void setLblSenha(JLabel lblSenha) {
        this.lblSenha = lblSenha;
    }

    public JLabel getLblSexo() {
        return lblSexo;
    }

    public void setLblSexo(JLabel lblSexo) {
        this.lblSexo = lblSexo;
    }

    public JLabel getLblTelefone() {
        return lblTelefone;
    }

    public void setLblTelefone(JLabel lblTelefone) {
        this.lblTelefone = lblTelefone;
    }

    public JPanel getPnlCadastroUsuario() {
        return pnlCadastroUsuario;
    }

    public void setPnlCadastroUsuario(JPanel pnlCadastroUsuario) {
        this.pnlCadastroUsuario = pnlCadastroUsuario;
    }

    public JPasswordField getPswRepeteSenha() {
        return pswRepeteSenha;
    }

    public void setPswRepeteSenha(JPasswordField pswRepeteSenha) {
        this.pswRepeteSenha = pswRepeteSenha;
    }

    public JPasswordField getPswSenha() {
        return pswSenha;
    }

    public void setPswSenha(JPasswordField pswSenha) {
        this.pswSenha = pswSenha;
    }

    public JTextField getTxtCpf() {
        return txtCpf;
    }

    public void setTxtCpf(JTextField txtCpf) {
        this.txtCpf = txtCpf;
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public void setTxtEmail(JTextField txtEmail) {
        this.txtEmail = txtEmail;
    }


    public JTextField getTxtId() {
        return txtId;
    }

    public void setTxtId(JTextField txtId) {
        this.txtId = txtId;
    }

    public JTextField getTxtNascimento() {
        return txtNascimento;
    }

    public void setTxtNascimento(JTextField txtNascimento) {
        this.txtNascimento = txtNascimento;
    }

    public JTextField getTxtNome() {
        return txtNome;
    }

    public void setTxtNome(JTextField txtNome) {
        this.txtNome = txtNome;
    }

    public JTextField getTxtTelefone() {
        return txtTelefone;
    }

    public void setTxtTelefone(JTextField txtTelefone) {
        this.txtTelefone = txtTelefone;
    }



}
