package Telas;

import Controller.ControllerServico;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.table.DefaultTableModel;

public class TelaServico extends javax.swing.JInternalFrame {

    private final ControllerServico controller;

    DefaultTableModel defTable;

    public TelaServico() throws SQLException {
        initComponents();
        this.controller = new ControllerServico(this);
        this.controller.AtualizarTabela();
        defTable = (DefaultTableModel) tblListaServico.getModel();
        btnAlterar.setVisible(false);
        btnExcluir.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GuiasServicos = new javax.swing.JTabbedPane();
        pnlDadosServicos = new javax.swing.JPanel();
        lblNovoProduto = new javax.swing.JLabel();
        spSeparador3 = new javax.swing.JSeparator();
        pnlInformacoes = new javax.swing.JPanel();
        lblIdServico = new javax.swing.JLabel();
        txtIdServico = new javax.swing.JTextField();
        lblNomeServi = new javax.swing.JLabel();
        txtNomeServi = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lblDescricaoPainel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtpDescricao = new javax.swing.JTextPane();
        btnAdicionar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblServico = new javax.swing.JLabel();
        spSeparador = new javax.swing.JSeparator();
        lblNomeServico = new javax.swing.JLabel();
        txtNomeServico = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaServico = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Dados Serviços");
        getContentPane().setLayout(null);

        GuiasServicos.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N

        pnlDadosServicos.setBackground(new java.awt.Color(78, 76, 76));

        lblNovoProduto.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        lblNovoProduto.setForeground(new java.awt.Color(255, 255, 255));
        lblNovoProduto.setText("Novo Serviço");

        spSeparador3.setForeground(new java.awt.Color(0, 0, 0));

        pnlInformacoes.setBackground(new java.awt.Color(78, 76, 76));
        pnlInformacoes.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));

        lblIdServico.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        lblIdServico.setForeground(new java.awt.Color(255, 255, 255));
        lblIdServico.setText("ID Serviço:");
        lblIdServico.setRequestFocusEnabled(false);

        txtIdServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdServicoActionPerformed(evt);
            }
        });

        lblNomeServi.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        lblNomeServi.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeServi.setText("Serviço:");
        lblNomeServi.setRequestFocusEnabled(false);

        txtNomeServi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeServiActionPerformed(evt);
            }
        });

        lblValor.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        lblValor.setForeground(new java.awt.Color(255, 255, 255));
        lblValor.setText("Valor:");
        lblValor.setRequestFocusEnabled(false);

        lblDescricaoPainel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        lblDescricaoPainel.setForeground(new java.awt.Color(255, 255, 255));
        lblDescricaoPainel.setText("Descrição:");
        lblDescricaoPainel.setRequestFocusEnabled(false);

        jScrollPane2.setViewportView(txtpDescricao);

        btnAdicionar.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInformacoesLayout = new javax.swing.GroupLayout(pnlInformacoes);
        pnlInformacoes.setLayout(pnlInformacoesLayout);
        pnlInformacoesLayout.setHorizontalGroup(
            pnlInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacoesLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pnlInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacoesLayout.createSequentialGroup()
                        .addGroup(pnlInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlInformacoesLayout.createSequentialGroup()
                                .addComponent(lblDescricaoPainel)
                                .addGap(419, 419, 419)
                                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(pnlInformacoesLayout.createSequentialGroup()
                        .addGroup(pnlInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdServico)
                            .addComponent(txtIdServico, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(pnlInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeServi, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeServi, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(pnlInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlInformacoesLayout.createSequentialGroup()
                                .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132))
                            .addGroup(pnlInformacoesLayout.createSequentialGroup()
                                .addComponent(txtValor)
                                .addGap(41, 41, 41))))))
        );
        pnlInformacoesLayout.setVerticalGroup(
            pnlInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacoesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlInformacoesLayout.createSequentialGroup()
                        .addGroup(pnlInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdServico, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeServi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(pnlInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdServico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeServi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlInformacoesLayout.createSequentialGroup()
                        .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricaoPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDadosServicosLayout = new javax.swing.GroupLayout(pnlDadosServicos);
        pnlDadosServicos.setLayout(pnlDadosServicosLayout);
        pnlDadosServicosLayout.setHorizontalGroup(
            pnlDadosServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosServicosLayout.createSequentialGroup()
                .addGroup(pnlDadosServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosServicosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNovoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spSeparador3, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDadosServicosLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(pnlInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlDadosServicosLayout.setVerticalGroup(
            pnlDadosServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosServicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosServicosLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(spSeparador3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNovoProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        GuiasServicos.addTab("Serviços novos", pnlDadosServicos);

        jPanel1.setBackground(new java.awt.Color(78, 76, 76));

        lblServico.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        lblServico.setForeground(new java.awt.Color(255, 255, 255));
        lblServico.setText("Serviços");

        spSeparador.setForeground(new java.awt.Color(0, 0, 0));

        lblNomeServico.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        lblNomeServico.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeServico.setText("Nome do Serviço:");
        lblNomeServico.setRequestFocusEnabled(false);

        txtNomeServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeServicoActionPerformed(evt);
            }
        });

        btnPesquisar.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tblListaServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Serviço", "Nome", "Valor", "Descrição"
            }
        ));
        jScrollPane1.setViewportView(tblListaServico);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNomeServico)
                                .addGap(18, 18, 18)
                                .addComponent(txtNomeServico, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblServico, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblServico))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(spSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNomeServico, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        GuiasServicos.addTab("Consultar", jPanel1);

        getContentPane().add(GuiasServicos);
        GuiasServicos.setBounds(0, 0, 750, 460);

        setBounds(0, 0, 754, 483);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeServicoActionPerformed

    private void txtIdServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdServicoActionPerformed

    private void txtNomeServiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeServiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeServiActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        try {
            this.controller.Inserir();
            JOptionPane.showMessageDialog(null, "Serviço Salvo Com sucesso!!, ");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possivel Salvar o Serviço, " + ex);
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        try {
            Connection conexao;
            PreparedStatement st;
            ResultSet resultado;

            Class.forName("com.mysql.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/bancobarbearia", "root", "123456");
            //Verifica o conteúdo do comboBox de tipo de relatório

            st = conexao.prepareStatement("SELECT * FROM servico WHERE nomeservico LIKE ?");
            st.setString(1, "%" + txtNomeServico.getText() + "%");
            resultado = st.executeQuery();

            defTable.setRowCount(0);
            while (resultado.next()) {
                Object[] linha = {resultado.getInt("idservico"), resultado.getString("nomeservico"),
                    resultado.getDouble("valor"), resultado.getString("descricao")};
                defTable.addRow(linha);

                btnAlterar.setVisible(true);
                btnExcluir.setVisible(true);
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca " + ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto" + ex.getMessage());
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        int Confirmacao = JOptionPane.showConfirmDialog(null, "Voce tem certeza que deseja Alterar o Serviço "
                + tblListaServico.getModel().getValueAt(0, 1) + "?");
        if (Confirmacao == 0) {
            try {
                this.controller.Alterar();
                this.controller.AtualizarTabela();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Não foi possivel Atualizar o servico" + ex.getMessage());
            }
        } else {
            txtNomeServico.requestFocus();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int Confirmacao = JOptionPane.showConfirmDialog(null, "Voce tem certeza que deseja Excluir o Serviço "
                + tblListaServico.getModel().getValueAt(0, 1) + "?");
        if (Confirmacao == 0) {
            try {
                this.controller.deleteServico();
                this.controller.AtualizarTabela();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Não Foi Possivel Excluir o Servico " + ex.getMessage());
            }
        } else {
            txtNomeServico.requestFocus();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane GuiasServicos;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDescricaoPainel;
    private javax.swing.JLabel lblIdServico;
    private javax.swing.JLabel lblNomeServi;
    private javax.swing.JLabel lblNomeServico;
    private javax.swing.JLabel lblNovoProduto;
    private javax.swing.JLabel lblServico;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel pnlDadosServicos;
    private javax.swing.JPanel pnlInformacoes;
    private javax.swing.JSeparator spSeparador;
    private javax.swing.JSeparator spSeparador3;
    private javax.swing.JTable tblListaServico;
    private javax.swing.JTextField txtIdServico;
    private javax.swing.JTextField txtNomeServi;
    private javax.swing.JTextField txtNomeServico;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextPane txtpDescricao;
    // End of variables declaration//GEN-END:variables

    public JTabbedPane getGuiasServicos() {
        return GuiasServicos;
    }

    public void setGuiasServicos(JTabbedPane GuiasServicos) {
        this.GuiasServicos = GuiasServicos;
    }

    public JButton getBtnAdicionar() {
        return btnAdicionar;
    }

    public void setBtnAdicionar(JButton btnAdicionar) {
        this.btnAdicionar = btnAdicionar;
    }

    public JButton getBtnAlterar() {
        return btnAlterar;
    }

    public void setBtnAlterar(JButton btnAlterar) {
        this.btnAlterar = btnAlterar;
    }

    public JButton getBtnExcluir() {
        return btnExcluir;
    }

    public void setBtnExcluir(JButton btnExcluir) {
        this.btnExcluir = btnExcluir;
    }

    public JButton getBtnPesquisar() {
        return btnPesquisar;
    }

    public void setBtnPesquisar(JButton btnPesquisar) {
        this.btnPesquisar = btnPesquisar;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JLabel getLblDescricaoPainel() {
        return lblDescricaoPainel;
    }

    public void setLblDescricaoPainel(JLabel lblDescricaoPainel) {
        this.lblDescricaoPainel = lblDescricaoPainel;
    }

    public JLabel getLblIdServico() {
        return lblIdServico;
    }

    public void setLblIdServico(JLabel lblIdServico) {
        this.lblIdServico = lblIdServico;
    }

    public JLabel getLblNomeServi() {
        return lblNomeServi;
    }

    public void setLblNomeServi(JLabel lblNomeServi) {
        this.lblNomeServi = lblNomeServi;
    }

    public JLabel getLblNomeServico() {
        return lblNomeServico;
    }

    public void setLblNomeServico(JLabel lblNomeServico) {
        this.lblNomeServico = lblNomeServico;
    }

    public JLabel getLblNovoProduto() {
        return lblNovoProduto;
    }

    public void setLblNovoProduto(JLabel lblNovoProduto) {
        this.lblNovoProduto = lblNovoProduto;
    }

    public JLabel getLblServico() {
        return lblServico;
    }

    public void setLblServico(JLabel lblServico) {
        this.lblServico = lblServico;
    }

    public JLabel getLblValor() {
        return lblValor;
    }

    public void setLblValor(JLabel lblValor) {
        this.lblValor = lblValor;
    }

    public JPanel getPnlDadosServicos() {
        return pnlDadosServicos;
    }

    public void setPnlDadosServicos(JPanel pnlDadosServicos) {
        this.pnlDadosServicos = pnlDadosServicos;
    }

    public JPanel getPnlInformacoes() {
        return pnlInformacoes;
    }

    public void setPnlInformacoes(JPanel pnlInformacoes) {
        this.pnlInformacoes = pnlInformacoes;
    }

    public JSeparator getSpSeparador() {
        return spSeparador;
    }

    public void setSpSeparador(JSeparator spSeparador) {
        this.spSeparador = spSeparador;
    }

    public JSeparator getSpSeparador3() {
        return spSeparador3;
    }

    public void setSpSeparador3(JSeparator spSeparador3) {
        this.spSeparador3 = spSeparador3;
    }

    public JTable getTblListaServico() {
        return tblListaServico;
    }

    public void setTblListaServico(JTable tblListaServico) {
        this.tblListaServico = tblListaServico;
    }

    public JTextField getTxtIdServico() {
        return txtIdServico;
    }

    public void setTxtIdServico(JTextField txtIdServico) {
        this.txtIdServico = txtIdServico;
    }

    public JTextField getTxtNomeServi() {
        return txtNomeServi;
    }

    public void setTxtNomeServi(JTextField txtNomeServi) {
        this.txtNomeServi = txtNomeServi;
    }

    public JTextField getTxtNomeServico() {
        return txtNomeServico;
    }

    public void setTxtNomeServico(JTextField txtNomeServico) {
        this.txtNomeServico = txtNomeServico;
    }

    public JTextField getTxtValor() {
        return txtValor;
    }

    public void setTxtValor(JTextField txtValor) {
        this.txtValor = txtValor;
    }

    public JTextPane getTxtpDescricao() {
        return txtpDescricao;
    }

    public void setTxtpDescricao(JTextPane txtpDescricao) {
        this.txtpDescricao = txtpDescricao;
    }

}
