package Telas;

import Controller.ViewClienteController;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class TelaClientes extends javax.swing.JInternalFrame {

    DefaultTableModel defTable;
    DefaultTableModel defTable1;

    private final ViewClienteController controller;

    public TelaClientes() throws SQLException {
        initComponents();
        controller = new ViewClienteController(this);
        defTable = (DefaultTableModel) tblConsultarCliente.getModel();
        defTable1 = (DefaultTableModel) tblCliente.getModel();
        iniciarTabela();
        btnAlterar.setVisible(false);
        btnExcluir.setVisible(false);

    }

    public TelaClientes(String nome) throws SQLException {
        initComponents();
        pnlCliente.remove(pnlCadastrarCliente);
        pnlCliente.remove(pnlConsultarCliente);
        controller = new ViewClienteController(this);
        defTable = (DefaultTableModel) tblConsultarCliente.getModel();
        defTable1 = (DefaultTableModel) tblCliente.getModel();
        iniciarTabela();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCliente = new javax.swing.JTabbedPane();
        pnlCadastrarCliente = new javax.swing.JPanel();
        spSeparador = new javax.swing.JSeparator();
        lblId = new javax.swing.JLabel();
        lblCadastroCliente = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNomeCompleto = new javax.swing.JLabel();
        txtNomeCompleto = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        boxGenero = new javax.swing.JComboBox<>();
        txtNascimento = new javax.swing.JTextField();
        lblNascimento = new javax.swing.JLabel();
        pnlConsultarCliente = new javax.swing.JPanel();
        lblConsultarCliente = new javax.swing.JLabel();
        spSeparador1 = new javax.swing.JSeparator();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        pdrConsultarCliente = new javax.swing.JScrollPane();
        tblConsultarCliente = new javax.swing.JTable();
        pnlListaCliente = new javax.swing.JPanel();
        lblListaCliente = new javax.swing.JLabel();
        pdrListaCliente = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        spSeparador2 = new javax.swing.JSeparator();

        setClosable(true);
        setTitle("Controle de Clientes");
        getContentPane().setLayout(null);

        pnlCliente.setBackground(new java.awt.Color(154, 118, 91));
        pnlCliente.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        pnlCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlClienteMouseClicked(evt);
            }
        });

        pnlCadastrarCliente.setBackground(new java.awt.Color(78, 76, 76));

        spSeparador.setForeground(new java.awt.Color(0, 0, 0));

        lblId.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblId.setText("ID");
        lblId.setToolTipText("");
        lblId.setAlignmentY(1.5F);

        lblCadastroCliente.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        lblCadastroCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblCadastroCliente.setText("Cadastro do Clientes");

        txtId.setFont(new java.awt.Font("Franklin Gothic Book", 0, 11)); // NOI18N

        lblNomeCompleto.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        lblNomeCompleto.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeCompleto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeCompleto.setText("Nome Completo:");
        lblNomeCompleto.setToolTipText("");
        lblNomeCompleto.setAlignmentY(1.5F);

        txtNomeCompleto.setFont(new java.awt.Font("Franklin Gothic Book", 0, 11)); // NOI18N

        lblSexo.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        lblSexo.setForeground(new java.awt.Color(255, 255, 255));
        lblSexo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSexo.setText("Sexo:");
        lblSexo.setToolTipText("");
        lblSexo.setAlignmentY(1.5F);

        txtCpf.setFont(new java.awt.Font("Franklin Gothic Book", 0, 11)); // NOI18N

        lblCpf.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        lblCpf.setForeground(new java.awt.Color(255, 255, 255));
        lblCpf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCpf.setText("CPF:");
        lblCpf.setToolTipText("");
        lblCpf.setAlignmentY(1.5F);

        lblEndereco.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        lblEndereco.setForeground(new java.awt.Color(255, 255, 255));
        lblEndereco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEndereco.setText("Endereço:");
        lblEndereco.setToolTipText("");
        lblEndereco.setAlignmentY(1.5F);

        txtEndereco.setFont(new java.awt.Font("Franklin Gothic Book", 0, 11)); // NOI18N

        lblEmail.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("E-mail:");
        lblEmail.setToolTipText("");
        lblEmail.setAlignmentY(1.5F);

        txtEmail.setFont(new java.awt.Font("Franklin Gothic Book", 0, 11)); // NOI18N

        lblTelefone.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTelefone.setText("Telefone:");
        lblTelefone.setToolTipText("");
        lblTelefone.setAlignmentY(1.5F);

        txtTelefone.setFont(new java.awt.Font("Franklin Gothic Book", 0, 11)); // NOI18N

        btnSalvar.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        boxGenero.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        boxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Não Binario" }));
        boxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxGeneroActionPerformed(evt);
            }
        });

        txtNascimento.setFont(new java.awt.Font("Franklin Gothic Book", 0, 11)); // NOI18N

        lblNascimento.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        lblNascimento.setForeground(new java.awt.Color(255, 255, 255));
        lblNascimento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNascimento.setText("Data de Nascimento:");
        lblNascimento.setToolTipText("");
        lblNascimento.setAlignmentY(1.5F);

        javax.swing.GroupLayout pnlCadastrarClienteLayout = new javax.swing.GroupLayout(pnlCadastrarCliente);
        pnlCadastrarCliente.setLayout(pnlCadastrarClienteLayout);
        pnlCadastrarClienteLayout.setHorizontalGroup(
            pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastrarClienteLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblCadastroCliente)
                .addGap(18, 18, 18)
                .addComponent(spSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlCadastrarClienteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblId)
                .addGap(10, 10, 10)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblNomeCompleto)
                .addGap(18, 18, 18)
                .addComponent(txtNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlCadastrarClienteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblNascimento)
                .addGap(10, 10, 10)
                .addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(lblCpf)
                .addGap(10, 10, 10)
                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlCadastrarClienteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblSexo)
                .addGap(18, 18, 18)
                .addComponent(boxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(lblEndereco)
                .addGap(10, 10, 10)
                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlCadastrarClienteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTelefone)
                .addGap(20, 20, 20)
                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(lblEmail)
                .addGap(26, 26, 26)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlCadastrarClienteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnSalvar)
                .addGap(37, 37, 37)
                .addComponent(btnCancelar))
        );
        pnlCadastrarClienteLayout.setVerticalGroup(
            pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastrarClienteLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCadastrarClienteLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(spSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCadastrarClienteLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCadastrarClienteLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pnlCliente.addTab("Cadastrar", pnlCadastrarCliente);

        pnlConsultarCliente.setBackground(new java.awt.Color(78, 76, 76));

        lblConsultarCliente.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        lblConsultarCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblConsultarCliente.setText("Consultar  Clientes");

        spSeparador1.setForeground(new java.awt.Color(0, 0, 0));

        lblNome.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNome.setText("Nome:");
        lblNome.setToolTipText("");
        lblNome.setAlignmentY(1.5F);

        txtNome.setFont(new java.awt.Font("Franklin Gothic Book", 0, 11)); // NOI18N

        btnPesquisar.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tblConsultarCliente.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 11)); // NOI18N
        tblConsultarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idCliente", "nome", "sexo", "nascimento", "endereco", "telefone", "email", "cpf"
            }
        ));
        tblConsultarCliente.setToolTipText("");
        tblConsultarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pdrConsultarCliente.setViewportView(tblConsultarCliente);

        javax.swing.GroupLayout pnlConsultarClienteLayout = new javax.swing.GroupLayout(pnlConsultarCliente);
        pnlConsultarCliente.setLayout(pnlConsultarClienteLayout);
        pnlConsultarClienteLayout.setHorizontalGroup(
            pnlConsultarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarClienteLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlConsultarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pdrConsultarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlConsultarClienteLayout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(18, 18, 18)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnPesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir))
                    .addGroup(pnlConsultarClienteLayout.createSequentialGroup()
                        .addComponent(lblConsultarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spSeparador1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        pnlConsultarClienteLayout.setVerticalGroup(
            pnlConsultarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarClienteLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlConsultarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblConsultarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spSeparador1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlConsultarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlConsultarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pdrConsultarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlCliente.addTab("Consultar Clientes", pnlConsultarCliente);

        pnlListaCliente.setBackground(new java.awt.Color(78, 76, 76));

        lblListaCliente.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        lblListaCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblListaCliente.setText("Lista de Clientes");

        tblCliente.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 11)); // NOI18N
        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCliente.setToolTipText("");
        tblCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pdrListaCliente.setViewportView(tblCliente);

        spSeparador2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlListaClienteLayout = new javax.swing.GroupLayout(pnlListaCliente);
        pnlListaCliente.setLayout(pnlListaClienteLayout);
        pnlListaClienteLayout.setHorizontalGroup(
            pnlListaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pdrListaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlListaClienteLayout.createSequentialGroup()
                        .addComponent(lblListaCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spSeparador2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnlListaClienteLayout.setVerticalGroup(
            pnlListaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblListaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spSeparador2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pdrListaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlCliente.addTab("Lista de Clientes", pnlListaCliente);

        getContentPane().add(pnlCliente);
        pnlCliente.setBounds(0, 5, 780, 430);

        setBounds(0, 0, 786, 464);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (txtNomeCompleto.getText().equals("")) {

            JOptionPane.showMessageDialog(null, " o campo Nome nao pode ficar em branco ");
            return;
        } else if (txtTelefone.getText().equals("")) {

            JOptionPane.showMessageDialog(null, " o campo Telefone nao pode ficar em branco ");
            return;

        } else if (txtId.getText().equals("")) {
            JOptionPane.showMessageDialog(null, " o campo ID nao pode ficar em branco ");
            return;

        } else
        
         try {
            this.controller.salvaCliente();
            JOptionPane.showMessageDialog(null, "Cliente Salvo Com Sucesso");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ocorreu um erro" + ex.getMessage());
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void boxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxGeneroActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
            this.controller.pesquisarCliente();
            btnAlterar.setVisible(true);
            btnExcluir.setVisible(true);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possivel Pesquisar o Cliente!!! " + ex);
        }


    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void pnlClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlClienteMouseClicked

    }//GEN-LAST:event_pnlClienteMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        int Confirmacao = JOptionPane.showConfirmDialog(null, "Voce tem certeza que deseja Alterar o Cliente "
                + tblConsultarCliente.getModel().getValueAt(0, 1) + "?");
        if (Confirmacao == 0) {
            try {

                this.controller.alterarCliente();
                JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso");
                iniciarTabela();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "não Foi possivel Alterar o cliente" + ex);
            }

        } else {
            txtNome.requestFocus();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int Confirmacao = JOptionPane.showConfirmDialog(null, "Voce tem certeza que deseja Excluir o Cliente "
                + tblConsultarCliente.getModel().getValueAt(0, 1) + "?");
        if (Confirmacao == 0) {
            try {
                this.controller.excluirCliente();
                JOptionPane.showMessageDialog(null, "Cliente excluído com sucesso");
                iniciarTabela();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Não foi possível excluir o cliente com este código" + ex);
            }
        } else {
            txtNome.requestFocus();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxGenero;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblCadastroCliente;
    private javax.swing.JLabel lblConsultarCliente;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblListaCliente;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeCompleto;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JScrollPane pdrConsultarCliente;
    private javax.swing.JScrollPane pdrListaCliente;
    private javax.swing.JPanel pnlCadastrarCliente;
    private javax.swing.JTabbedPane pnlCliente;
    private javax.swing.JPanel pnlConsultarCliente;
    private javax.swing.JPanel pnlListaCliente;
    private javax.swing.JSeparator spSeparador;
    private javax.swing.JSeparator spSeparador1;
    private javax.swing.JSeparator spSeparador2;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTable tblConsultarCliente;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeCompleto;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getBoxGenero() {
        return boxGenero;
    }

    public void setBoxGenero(JComboBox<String> boxGenero) {
        this.boxGenero = boxGenero;
    }

    public JButton getBtnAlterar() {
        return btnAlterar;
    }

    public void setBtnAlterar(JButton btnAlterar) {
        this.btnAlterar = btnAlterar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnExcluir() {
        return btnExcluir;
    }

    public void setBtnExcluir(JButton btnExcluir) {
        this.btnExcluir = btnExcluir;
    }

    public JButton getBtnPesquisar() {
        return btnPesquisar;
    }

    public void setBtnPesquisar(JButton btnPesquisar) {
        this.btnPesquisar = btnPesquisar;
    }

    public JButton getBtnSalvar() {
        return btnSalvar;
    }

    public void setBtnSalvar(JButton btnSalvar) {
        this.btnSalvar = btnSalvar;
    }

    public JLabel getLblCadastroCliente() {
        return lblCadastroCliente;
    }

    public void setLblCadastroCliente(JLabel lblCadastroCliente) {
        this.lblCadastroCliente = lblCadastroCliente;
    }

    public JLabel getLblConsultarCliente() {
        return lblConsultarCliente;
    }

    public void setLblConsultarCliente(JLabel lblConsultarCliente) {
        this.lblConsultarCliente = lblConsultarCliente;
    }

    public JLabel getLblCpf() {
        return lblCpf;
    }

    public void setLblCpf(JLabel lblCpf) {
        this.lblCpf = lblCpf;
    }

    public JLabel getLblEmail() {
        return lblEmail;
    }

    public void setLblEmail(JLabel lblEmail) {
        this.lblEmail = lblEmail;
    }

    public JLabel getLblEndereco() {
        return lblEndereco;
    }

    public void setLblEndereco(JLabel lblEndereco) {
        this.lblEndereco = lblEndereco;
    }

    public JLabel getLblId() {
        return lblId;
    }

    public void setLblId(JLabel lblId) {
        this.lblId = lblId;
    }

    public JLabel getLblListaCliente() {
        return lblListaCliente;
    }

    public void setLblListaCliente(JLabel lblListaCliente) {
        this.lblListaCliente = lblListaCliente;
    }

    public JLabel getLblNascimento() {
        return lblNascimento;
    }

    public void setLblNascimento(JLabel lblNascimento) {
        this.lblNascimento = lblNascimento;
    }

    public JLabel getLblNome() {
        return lblNome;
    }

    public void setLblNome(JLabel lblNome) {
        this.lblNome = lblNome;
    }

    public JLabel getLblNomeCompleto() {
        return lblNomeCompleto;
    }

    public void setLblNomeCompleto(JLabel lblNomeCompleto) {
        this.lblNomeCompleto = lblNomeCompleto;
    }

    public JLabel getLblSexo() {
        return lblSexo;
    }

    public void setLblSexo(JLabel lblSexo) {
        this.lblSexo = lblSexo;
    }

    public JLabel getLblTelefone() {
        return lblTelefone;
    }

    public void setLblTelefone(JLabel lblTelefone) {
        this.lblTelefone = lblTelefone;
    }

    public JScrollPane getPdrConsultarCliente() {
        return pdrConsultarCliente;
    }

    public void setPdrConsultarCliente(JScrollPane pdrConsultarCliente) {
        this.pdrConsultarCliente = pdrConsultarCliente;
    }

    public JScrollPane getPdrListaCliente() {
        return pdrListaCliente;
    }

    public void setPdrListaCliente(JScrollPane pdrListaCliente) {
        this.pdrListaCliente = pdrListaCliente;
    }

    public JPanel getPnlCadastrarCliente() {
        return pnlCadastrarCliente;
    }

    public void setPnlCadastrarCliente(JPanel pnlCadastrarCliente) {
        this.pnlCadastrarCliente = pnlCadastrarCliente;
    }

    public JTabbedPane getPnlCliente() {
        return pnlCliente;
    }

    public void setPnlCliente(JTabbedPane pnlCliente) {
        this.pnlCliente = pnlCliente;
    }

    public JPanel getPnlConsultarCliente() {
        return pnlConsultarCliente;
    }

    public void setPnlConsultarCliente(JPanel pnlConsultarCliente) {
        this.pnlConsultarCliente = pnlConsultarCliente;
    }

    public JPanel getPnlListaCliente() {
        return pnlListaCliente;
    }

    public void setPnlListaCliente(JPanel pnlListaCliente) {
        this.pnlListaCliente = pnlListaCliente;
    }

    public JSeparator getSpSeparador() {
        return spSeparador;
    }

    public void setSpSeparador(JSeparator spSeparador) {
        this.spSeparador = spSeparador;
    }

    public JSeparator getSpSeparador1() {
        return spSeparador1;
    }

    public void setSpSeparador1(JSeparator spSeparador1) {
        this.spSeparador1 = spSeparador1;
    }

    public JSeparator getSpSeparador2() {
        return spSeparador2;
    }

    public void setSpSeparador2(JSeparator spSeparador2) {
        this.spSeparador2 = spSeparador2;
    }

    public JTable getTblCliente() {
        return tblCliente;
    }

    public void setTblCliente(JTable tblCliente) {
        this.tblCliente = tblCliente;
    }

    public JTable getTblConsultarCliente() {
        return tblConsultarCliente;
    }

    public void setTblConsultarCliente(JTable tblConsultarCliente) {
        this.tblConsultarCliente = tblConsultarCliente;
    }

    public JTextField getTxtCpf() {
        return txtCpf;
    }

    public void setTxtCpf(JTextField txtCpf) {
        this.txtCpf = txtCpf;
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public void setTxtEmail(JTextField txtEmail) {
        this.txtEmail = txtEmail;
    }

    public JTextField getTxtEndereco() {
        return txtEndereco;
    }

    public void setTxtEndereco(JTextField txtEndereco) {
        this.txtEndereco = txtEndereco;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public void setTxtId(JTextField txtId) {
        this.txtId = txtId;
    }

    public JTextField getTxtNascimento() {
        return txtNascimento;
    }

    public void setTxtNascimento(JTextField txtNascimento) {
        this.txtNascimento = txtNascimento;
    }

    public JTextField getTxtNome() {
        return txtNome;
    }

    public void setTxtNome(JTextField txtNome) {
        this.txtNome = txtNome;
    }

    public JTextField getTxtNomeCompleto() {
        return txtNomeCompleto;
    }

    public void setTxtNomeCompleto(JTextField txtNomeCompleto) {
        this.txtNomeCompleto = txtNomeCompleto;
    }

    public JTextField getTxtTelefone() {
        return txtTelefone;
    }

    public void setTxtTelefone(JTextField txtTelefone) {
        this.txtTelefone = txtTelefone;
    }

    private void iniciarTabela() throws SQLException {

        this.controller.iniciarTabela();

        try {
            Connection conexao;
            PreparedStatement st;
            ResultSet resultado;

            Class.forName("com.mysql.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/bancobarbearia", "root", "123456");
            //Verifica o conteúdo do comboBox de tipo de relatório

            st = conexao.prepareStatement("SELECT * FROM cliente ");
            resultado = st.executeQuery();

            defTable1.setRowCount(0);
            while (resultado.next()) {
                Object[] linha = {resultado.getInt("idcliente"), resultado.getString("Nome"),
                    resultado.getString("email")};
                defTable1.addRow(linha);
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca " + ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto" + ex.getMessage());
        }
    }

}
